spring:
  application:
    name: fsm-shipping
  datasource:
    url: jdbc:h2:mem:fsm
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest

rabbitmq:
  queues:
    shipping:
      queue: shipping-queue
      exchange: fsm
      routing-key: shipping-queue