spring:
  application:
    name: fsm-shipping
  datasource:
    url: jdbc:h2:mem:fsm
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
